version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videoapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: videoapp
      NEXTAUTH_SECRET: supersecretkey123
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  mysql_data:
