version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: FEotrNqzkTnGmPrvgeOhmJnvHeaLecHE
      MYSQL_DATABASE: railway
      MYSQLUSER: root
      MYSQLPASSWORD: FEotrNqzkTnGmPrvgeOhmJnvHeaLecHE
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    environment:
      MYSQLHOST: mysql.railway.internal
      MYSQLUSER: root
      MYSQLPASSWORD: FEotrNqzkTnGmPrvgeOhmJnvHeaLecHE
      MYSQL_DATABASE: railway
      NEXTAUTH_SECRET: supersecretkey123
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  mysql_data:
